 USE CURSOBIGDATA;

 ---Fichero dentro del HDFS
 --LOAD DATA INPATH '/datos/1987.csv.bz2' OVERWRITE INTO TABLE VUELOS;

 -- Exportar registros de Hive a Local
 --INSERT OVERWRITE LOCAL DIRECTORY '/tmp/vuelos'
 --ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
 --LINES TERMINATED BY '\n' 
 --SELECT * FROM VUELOS;


  ---Fichero dentro del HDFS
INSERT OVERWRITE TABLE VUELOS_CLUSTER SELECT * FROM VUELOS;