/*
 DROP TABLE CURSO.TITULARES;
 DROP TABLE CURSO.MOVIMIENTOS;
 DROP TABLE CURSO.CUENTAS;
 DROP TABLE CURSO.CLIENTES;

 DROP SEQUENCE seq_id_mov;

 DROP SCHEMA CURSO;
*/

CREATE SCHEMA CURSO;

CREATE TABLE CURSO.CLIENTES (
	NIF	VARCHAR(11) NOT NULL,
	NOMBRE VARCHAR(20),
	APELLIDOS VARCHAR(40),
	DOMICILIO VARCHAR(40),
	CP INTEGER,
	CIUDAD VARCHAR(40),
	PROVINCIA VARCHAR(20),
	FECHA_NACIMIENTO DATE,
	FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT CLIENTES_PK PRIMARY KEY (NIF)
);

CREATE TABLE CURSO.CUENTAS (
	BANCO CHAR(4) NOT NULL,
	SUCURSAL CHAR(4) NOT NULL,
	DC CHAR(2) NOT NULL,
	NUMERO CHAR(10) NOT NULL,
	FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	SALDO DECIMAL(18,2) DEFAULT 0.00,
	LIMITE_DESCUBIERTO DECIMAL(18,2) DEFAULT 0.00,
	LIMITE_OPERACION DECIMAL(18,2) DEFAULT 0.00,
	CONSTRAINT CUENTAS_PK PRIMARY KEY(BANCO, SUCURSAL, DC, NUMERO)
);

CREATE SEQUENCE seq_id_mov;

CREATE TABLE CURSO.MOVIMIENTOS (
	ID INTEGER NOT NULL DEFAULT nextval('seq_id_mov'),
	BANCO CHAR(4) NOT NULL,
	SUCURSAL CHAR(4) NOT NULL,
	DC CHAR(2) NOT NULL,
	NUMERO CHAR(10) NOT NULL,
	FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DESCRIPCION VARCHAR(1024),
	CONSTRAINT MOVIMIENTOS_PK PRIMARY KEY (ID),
	CONSTRAINT MOVIMIENTOS_CUENTAS_FK FOREIGN KEY (BANCO, SUCURSAL, DC, NUMERO) REFERENCES CURSO.CUENTAS(BANCO, SUCURSAL, DC, NUMERO)

);

CREATE TABLE CURSO.TITULARES (
	NIF	VARCHAR(9) NOT NULL,
	BANCO CHAR(4) NOT NULL,
	SUCURSAL CHAR(4) NOT NULL,
	DC CHAR(2) NOT NULL,
	NUMERO CHAR(10) NOT NULL,
	FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT TITULARES_PK PRIMARY KEY (NIF, BANCO, SUCURSAL, DC, NUMERO),
	CONSTRAINT TITULARES_CUENTAS_FK FOREIGN KEY (BANCO, SUCURSAL, DC, NUMERO) REFERENCES CURSO.CUENTAS (BANCO, SUCURSAL, DC, NUMERO),
	CONSTRAINT TITULARES_CLIENTES_FK FOREIGN KEY (NIF) REFERENCES CURSO.CLIENTES(NIF)

);

CREATE TABLE CURSO.CLIENTES (
	NIF	VARCHAR(11) NOT NULL,
	NOMBRE VARCHAR(20),
	APELLIDOS VARCHAR(40),
	DOMICILIO VARCHAR(40),
	CP INTEGER,
	CIUDAD VARCHAR(40),
	PROVINCIA VARCHAR(20),
	FECHA_NACIMIENTO DATE,
	FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT CLIENTES_PK PRIMARY KEY (NIF)
);

# http://www.mockaroo.com/