/*
 DROP TABLE CURSO.TITULARES;
 DROP TABLE CURSO.MOVIMIENTOS;
 DROP TABLE CURSO.CUENTAS;
 DROP TABLE CURSO.CLIENTES;

 DROP SEQUENCE seq_id_mov;

 DROP SCHEMA CURSO;
*/


CREATE TABLE CLIENTES_HADOOP (
	NIF	VARCHAR(11) NOT NULL,
	NOMBRE VARCHAR(20),
	APELLIDOS VARCHAR(40),
	DOMICILIO VARCHAR(40),
	CP INTEGER,
	CIUDAD VARCHAR(40),
	PROVINCIA VARCHAR(20),
	FECHA_NACIMIENTO DATE,
	FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT CLIENTES_HADOOP_PK PRIMARY KEY (NIF)
);